# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LeetcodeSr < Formula
  desc "CLI for LeetCode Spaced Repetition Tracker"
  homepage "https://github.com/VinMeld/leetcode-space-repition"
  version "2.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/VinMeld/leetcode-space-repition/releases/download/v2.3.1/leetcode-sr_2.3.1_darwin_amd64.tar.gz"
      sha256 "ee559f4815ad44cf481f81c7c213fd29c20fa9b15a71948c56978d80a0f2c630"

      def install
        bin.install "leetcode-sr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/VinMeld/leetcode-space-repition/releases/download/v2.3.1/leetcode-sr_2.3.1_darwin_arm64.tar.gz"
      sha256 "90a0cd7d47da732e12870b1c9b525d398c34501b1726141f61c2e9523a55f5b9"

      def install
        bin.install "leetcode-sr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/VinMeld/leetcode-space-repition/releases/download/v2.3.1/leetcode-sr_2.3.1_linux_amd64.tar.gz"
      sha256 "aef0c7f147ed0c9b39dc2d0dbc20626fb962a3b87fdc4ad0be350afcdcd27e7d"
      def install
        bin.install "leetcode-sr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/VinMeld/leetcode-space-repition/releases/download/v2.3.1/leetcode-sr_2.3.1_linux_arm64.tar.gz"
      sha256 "f95e01e1e042cb67bcd3dd37658140a842b22cdc0a8ac9e64eba42a6e83afd5d"
      def install
        bin.install "leetcode-sr"
      end
    end
  end

  test do
    system "#{bin}/leetcode-sr", "--version"
  end
end
