# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LeetcodeSr < Formula
  desc "CLI for LeetCode Spaced Repetition Tracker"
  homepage "https://github.com/VinMeld/leetcode-space-repition"
  version "2.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/VinMeld/leetcode-space-repition/releases/download/v2.0.2/leetcode-sr_2.0.2_darwin_amd64.tar.gz"
      sha256 "7894fb579f396b6d0e7f5147c94ea8cb9a5c2b4bf345b669d7b155dcc7ca114c"

      def install
        bin.install "leetcode-sr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/VinMeld/leetcode-space-repition/releases/download/v2.0.2/leetcode-sr_2.0.2_darwin_arm64.tar.gz"
      sha256 "feb1e6eeebfc7684656c99cb922ff3feab839ccc1df683e1bd8b3c66c556e198"

      def install
        bin.install "leetcode-sr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/VinMeld/leetcode-space-repition/releases/download/v2.0.2/leetcode-sr_2.0.2_linux_amd64.tar.gz"
      sha256 "dfc7fd032d1df6b4f75fe0c8cd429fb3c272578ecc997d35bde6bb50541b5141"
      def install
        bin.install "leetcode-sr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/VinMeld/leetcode-space-repition/releases/download/v2.0.2/leetcode-sr_2.0.2_linux_arm64.tar.gz"
      sha256 "90546f379196843529aac7e3d29a77269504bb16d46d8e36a811e842abdfe22d"
      def install
        bin.install "leetcode-sr"
      end
    end
  end

  test do
    system "#{bin}/leetcode-sr", "--version"
  end
end
